# application.yml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: SEU USUARIO AQUI
    password: SUA SENHA AQUI
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
  
server:
  port: 8080
